services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    expose:
      - 3001
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    expose:
      - 8080