name: Build App
on:
  push:
    branches: ["main"]
jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: start backend service
        working-directory: ./backend
        run: sudo docker build -t backend . && sudo docker run --rm -d backend
  build-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        working-directory: ./frontend
        run: npm run i
      - name: build frontend
        working-directory: ./frontend
        run: npm run build --base /var/www/
