name: Build App
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: start backend service
        run: cd backend/ && sudo docker build -t backend . && sudo docker run --rm backend
      - name: build frontend
        run: cd ../frontend && npm run build --base /var/www/
