name: Build App
on:
  push:
    branches: ["main"]
jobs:
  build-backend:
    runs-on: self-hosted
    env:
      PORT: 3001
      CERT_PATH: /etc/letsencrypt/live/
      DOMAIN: overengineeredweatherapp.cloud/
      CERT: fullchain.pem
      KEY: privkey.pem
    steps:
      - uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        working-directory: ./backend
        run: npm install
      - name: Create .env file
        working-directory: ./backend
        run: |
          touch .env
          echo PORT=${{ env.PORT }} >> .env
          echo CERT_PATH=CERT_PATH >> .env
          echo DOMAIN=DOMAIN >> .env
          echo CERT=CERT >> .env
          echo KEY=KEY >> .env
      - name: build project
        working-directory: ./backend
        run: npm run build
      - name: start backend service
        working-directory: ./backend
        run: npm run start
  build-frontend:
    runs-on: self-hosted
    env:
      VITE_AWS_IP: 13.50.111.21
      VITE_API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        working-directory: ./frontend
        run: npm install
      - name: build project
        working-directory: ./frontend
        run: npm run build
      - name: copy project to www
        working-directory: ./frontend
        run: sudo cp -rv dist/ /var/www/
