name: Build App
on:
  push:
    branches: ["main"]
jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: start backend service
        working-directory: ./backend
        run: sudo docker build -t backend . && sudo docker run --rm -d backend
  build-frontend:
    runs-on: self-hosted
    env:
      VITE_AWS_IP: 13.50.111.21
      VITE_API_PORT: 3000
    steps:
      - uses: actions/checkout@v3
      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        working-directory: ./frontend
        run: npm install
      - name: build project
        working-directory: ./frontend
        run: npm run build
      - name: copy project to www
        working-directory: ./frontend
        run: sudo cp -rv dist/ /var/www/
